import type { Category } from "@/lib/types";

export const DATA: Category[] = [
	{
		key: "py",
		label: "Python Data Libraries",
		items: [
			{
				id: "pandas",
				customizedComponent: false,
				name: "Pandas",
				file: "Python Data Libraries/Pandas_Cheatsheet.md",
				status: "solid",
				tagline: "I/O, profiling, cleaning, reshaping, joins, ETL patterns",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "polars",
				customizedComponent: false,
				name: "Polars",
				file: "Python Data Libraries/Polars_Cheat_Sheet.md",
				status: "solid",
				tagline: "Eager vs lazy, SQL context, expressions, window functions",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "pyspark",
				customizedComponent: false,
				name: "PySpark",
				file: "Python Data Libraries/PySpark_Cheatsheet.md",
				status: "solid",
				tagline: "Lazy evaluation, UDFs, broadcast/accumulators, skew handling",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "jupyter",
				customizedComponent: false,
				name: "Jupyter Notebook",
				file: "Python Data Libraries/Jupyter_Notebook_Power_Tips.md",
				status: "solid",
				tagline: "Magic commands, extensions, reproducibility habits",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "dsa",
		label: "Data Structures & Algorithms",
		items: [
			{
				id: "dsa-time-space",
				customizedComponent: false,
				name: "Time & Space Complexity",
				file: "Data Structure and Algo/Time_Space_Complexity.md",
				status: "solid",
				tagline:
					"Big-O and the complexity classes every other topic here assumes",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-hashmaps",
				customizedComponent: false,
				name: "Hashmaps / Sets",
				file: "Data Structure and Algo/Hashmaps_Sets.md",
				status: "solid",
				tagline: "Hash-based lookup — trading space for O(1) average time",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-two-pointers",
				customizedComponent: false,
				name: "Two Pointers",
				file: "Data Structure and Algo/Two_Pointers.md",
				status: "solid",
				tagline: "Two indices moving through a sequence to avoid nested loops",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-stacks",
				customizedComponent: false,
				name: "Stacks",
				file: "Data Structure and Algo/Stacks.md",
				status: "solid",
				tagline:
					"LIFO structure for matching, backtracking state, and monotonic sequences",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-linked-list",
				customizedComponent: false,
				name: "Linked List",
				file: "Data Structure and Algo/Linked_List.md",
				status: "solid",
				tagline: "Pointer-based sequences — reversal, cycle detection, merging",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-binary-search",
				customizedComponent: false,
				name: "Binary Search",
				file: "Data Structure and Algo/Binary_Search.md",
				status: "solid",
				tagline:
					'O(log n) search, and the problem shapes that aren\u2019t obviously "search a sorted array"',
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-sliding-window",
				customizedComponent: false,
				name: "Sliding Window",
				file: "Data Structure and Algo/Sliding_Window.md",
				status: "solid",
				tagline:
					"A contiguous window that grows and shrinks to avoid re-scanning",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-trees",
				customizedComponent: false,
				name: "Trees",
				file: "Data Structure and Algo/Trees.md",
				status: "solid",
				tagline:
					"Hierarchical structures — traversal orders, BSTs, and the recursion template behind both",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-heaps",
				customizedComponent: false,
				name: "Heaps",
				file: "Data Structure and Algo/Heaps.md",
				status: "solid",
				tagline:
					"Priority queues — always-O(log n) access to the min or max element",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-backtracking",
				customizedComponent: false,
				name: "Recursive Backtracking",
				file: "Data Structure and Algo/Recursive_Backtracking.md",
				status: "solid",
				tagline:
					"Choose, explore, undo — for permutations, combinations, and constraint search",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dsa-graphs",
				customizedComponent: false,
				name: "Graphs",
				file: "Data Structure and Algo/Graphs.md",
				status: "solid",
				tagline: "Traversal, shortest paths, and topological ordering",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "eng",
		label: "Engineering Fundamentals",
		items: [
			{
				id: "depatterns",
				customizedComponent: true,
				name: "Data Engineering Patterns",
				file: "Data_Engineering_Patterns.md",
				status: "solid",
				tagline:
					"Architectural and pipeline-design patterns, independent of any specific tool",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "fastapi",
				customizedComponent: false,
				name: "FastAPI",
				file: "FastAPI_Cheatsheet.md",
				status: "solid",
				tagline:
					"Modern Python APIs with async endpoints, validation, and dependency injection",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "regex",
				customizedComponent: false,
				name: "Regex",
				file: "regex.md",
				status: "solid",
				tagline:
					"Pattern syntax for text parsing, validation, and log/data cleaning",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "cli-data-wrangling",
				customizedComponent: false,
				name: "Command-line Data Wrangling",
				file: "Command_line_Data_Wrangling.md",
				status: "planned",
				tagline: "grep, awk, sed, jq for quick data checks outside pandas",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "designpatterns",
		label: "Design Patterns",
		slug: "design-patterns",
		subcategories: [
			{
				key: "creational",
				label: "Creational",
				slug: "creational",
				status: "solid",
				tagline:
					"Patterns for object creation — decoupling instantiation from usage",
				covers: "",
				items: [
					{
						id: "dp-singleton",
						customizedComponent: false,
						name: "Singleton",
						file: "Design Patterns/singleton.md",
						slug: "singleton",
						status: "solid",
						tagline:
							"Ensure a class has only one instance, with global access to it",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-factory-method",
						customizedComponent: false,
						name: "Factory",
						file: "Design Patterns/factory.md",
						slug: "factory",
						status: "solid",
						tagline: "Defer object instantiation to subclasses",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-abstract-factory",
						customizedComponent: false,
						name: "Abstract Factory",
						file: "Design Patterns/abstract-factory.md",
						slug: "abstract-factory",
						status: "solid",
						tagline:
							"Produce families of related objects without specifying concrete classes",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-builder",
						customizedComponent: false,
						name: "Builder",
						file: "Design Patterns/builder.md",
						slug: "builder",
						status: "solid",
						tagline:
							"Separate the construction of a complex object from its representation",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-prototype",
						customizedComponent: false,
						name: "Prototype",
						file: "Design Patterns/prototype.md",
						slug: "prototype",
						status: "solid",
						tagline: "Create new objects by copying an existing instance",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "structural",
				label: "Structural",
				slug: "structural",
				status: "solid",
				tagline:
					"Patterns for composing objects and classes into larger structures",
				covers: "",
				items: [
					{
						id: "dp-adapter",
						customizedComponent: false,
						name: "Adapter",
						file: "Design Patterns/adapter.md",
						slug: "adapter",
						status: "solid",
						tagline: "Convert one interface into another that a client expects",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-bridge",
						customizedComponent: false,
						name: "Bridge",
						file: "Design Patterns/bridge.md",
						slug: "bridge",
						status: "solid",
						tagline:
							"Decouple an abstraction from its implementation so both can vary independently",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-composite",
						customizedComponent: false,
						name: "Composite",
						file: "Design Patterns/composite.md",
						slug: "composite",
						status: "solid",
						tagline:
							"Compose objects into tree structures and treat individual objects and compositions uniformly",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-decorator",
						customizedComponent: false,
						name: "Decorator",
						file: "Design Patterns/decorator.md",
						slug: "decorator",
						status: "solid",
						tagline:
							"Attach additional responsibilities to an object dynamically",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-facade",
						customizedComponent: false,
						name: "Facade",
						file: "Design Patterns/facade.md",
						slug: "facade",
						status: "solid",
						tagline: "Provide a simplified interface to a complex subsystem",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-flyweight",
						customizedComponent: false,
						name: "Flyweight",
						file: "Design Patterns/flyweight.md",
						slug: "flyweight",
						status: "solid",
						tagline:
							"Share common state across many objects to reduce memory footprint",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-proxy",
						customizedComponent: false,
						name: "Proxy",
						file: "Design Patterns/proxy.md",
						slug: "proxy",
						status: "solid",
						tagline:
							"Provide a stand-in for another object to control access to it",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "behavioural",
				label: "Behavioural",
				slug: "behavioural",
				status: "solid",
				tagline:
					"Patterns for communication and responsibility between objects",
				covers: "",
				items: [
					{
						id: "dp-chain-of-responsibility",
						customizedComponent: false,
						name: "Chain of Responsibility",
						file: "Design Patterns/chain-of-responsibility.md",
						slug: "chain-of-responsibility",
						status: "solid",
						tagline:
							"Pass a request along a chain of handlers until one handles it",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-command",
						customizedComponent: false,
						name: "Command",
						file: "Design Patterns/command.md",
						slug: "command",
						status: "solid",
						tagline:
							"Encapsulate a request as an object, allowing queuing, logging, and undo",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-interpreter",
						customizedComponent: false,
						name: "Interpreter",
						file: "Design Patterns/interpreter.md",
						slug: "interpreter",
						status: "solid",
						tagline:
							"Define a grammar and an interpreter for a simple language",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-iterator",
						customizedComponent: false,
						name: "Iterator",
						file: "Design Patterns/iterator.md",
						slug: "iterator",
						status: "solid",
						tagline:
							"Access elements of a collection sequentially without exposing its structure",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-mediator",
						customizedComponent: false,
						name: "Mediator",
						file: "Design Patterns/mediator.md",
						slug: "mediator",
						status: "solid",
						tagline:
							"Define an object that encapsulates how a set of objects interact",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-memento",
						customizedComponent: false,
						name: "Memento",
						file: "Design Patterns/memento.md",
						slug: "memento",
						status: "solid",
						tagline:
							"Capture and externalize an object\u2019s internal state to restore it later",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-observer",
						customizedComponent: false,
						name: "Observer",
						file: "Design Patterns/observer.md",
						slug: "observer",
						status: "solid",
						tagline:
							"Notify dependents automatically when one object changes state",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dp-state",
						customizedComponent: false,
						name: "State",
						file: "Design Patterns/state.md",
						slug: "state",
						status: "solid",
						tagline:
							"Let an object alter its behavior when its internal state changes",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
		],
	},
	// ---- Databases & Data Modeling ----
	{
		key: "db",
		label: "Data Warehouses & Databases",
		items: [
			{
				id: "postgres",
				customizedComponent: false,
				name: "PostgreSQL",
				file: "Databases/PostgreSQL_Cheatsheet.md",
				status: "solid",
				tagline: "psql, window functions, JSON/JSONB, arrays, indexing",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "mysql",
				customizedComponent: false,
				name: "MySQL",
				file: "Databases/MySQL_Cheatsheet.md",
				status: "solid",
				tagline: "CRUD, joins, window functions, JSON, RFM, cohort/YoY",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sqlalchemy",
				customizedComponent: false,
				name: "SQLAlchemy",
				file: "Databases/SQLAlchemy.md",
				status: "solid",
				tagline: "The thinnest file in the set, written entirely in 1.x style",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "bigquery",
				customizedComponent: false,
				name: "Google BigQuery",
				file: "Databases/BigQuery_Cheatsheet.md",
				status: "solid",
				tagline:
					"GCP's serverless warehouse — partitioning, clustering, slots, cost control",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "lakehouse-formats",
				customizedComponent: false,
				name: "Delta Lake / Apache Iceberg / Hudi",
				file: "Databases/Lakehouse_Table_Formats.md",
				status: "solid",
				tagline: "Lakehouse table formats — ACID on top of object storage",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "modeling",
		label: "Data Modeling",
		items: [
			{
				id: "modeling-fundamentals",
				customizedComponent: false,
				name: "Fundamentals",
				file: "Data Modeling/01-fundamentals.md",
				status: "solid",
				tagline: "The foundations, vocabulary, and goals of data modeling",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-conceptual",
				customizedComponent: false,
				name: "Conceptual Data Modeling",
				file: "Data Modeling/02-conceptual-modeling.md",
				status: "solid",
				tagline:
					"Represent business concepts and relationships without implementation details",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-logical",
				customizedComponent: false,
				name: "Logical Data Modeling",
				file: "Data Modeling/03-logical-modeling.md",
				status: "solid",
				tagline:
					"Define precise attributes, keys, and rules independent of a database engine",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-normalization",
				customizedComponent: false,
				name: "Normalization & Denormalization",
				file: "Data Modeling/04-normalization-denormalization.md",
				status: "solid",
				tagline:
					"Balance data integrity, storage efficiency, and query performance",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-physical",
				customizedComponent: false,
				name: "Physical Data Modeling",
				file: "Data Modeling/05-physical-modeling.md",
				status: "solid",
				tagline:
					"Translate a logical model into an efficient database implementation",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-relational",
				customizedComponent: false,
				name: "Relational Modeling",
				file: "Data Modeling/06-relational-modeling.md",
				status: "solid",
				tagline:
					"Design tables and relationships for relational database systems",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-dimensional",
				customizedComponent: false,
				name: "Dimensional Modeling",
				file: "Data Modeling/07-dimensional-modeling.md",
				status: "solid",
				tagline: "Model analytical data for reporting and warehouse workloads",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-nosql",
				customizedComponent: false,
				name: "NoSQL Data Modeling",
				file: "Data Modeling/08-nosql-modeling.md",
				status: "solid",
				tagline:
					"Design around access patterns in document, key-value, wide-column, and graph stores",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-notations-tools",
				customizedComponent: false,
				name: "Notations & Tools",
				file: "Data Modeling/09-notations-tools.md",
				status: "solid",
				tagline:
					"Communicate and maintain models with the right diagrams and tooling",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "modeling-best-practices",
				customizedComponent: false,
				name: "Best Practices & Anti-patterns",
				file: "Data Modeling/10-best-practices-antipatterns.md",
				status: "solid",
				tagline:
					"Review models for clarity, correctness, maintainability, and operational fit",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "data-modeling-examples",
				customizedComponent: true,
				name: "Examples",
				status: "solid",
				tagline:
					"Real-world data modeling examples for different domains and use cases",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	// ---- Data Engineering & Infrastructure ----
	{
		key: "etl",
		label: "ETL / ELT",
		items: [
			{
				id: "etl-fundamentals",
				customizedComponent: false,
				name: "Fundamentals & Core Concepts",
				file: "ETLxELT/01-fundamentals.md",
				status: "solid",
				tagline: "The foundations of reliable data movement",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-extract",
				customizedComponent: false,
				name: "Extract",
				file: "ETLxELT/02-extract.md",
				status: "solid",
				tagline: "Getting trustworthy data out of source systems",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-transform",
				customizedComponent: false,
				name: "Transform",
				file: "ETLxELT/03-transform.md",
				status: "solid",
				tagline: "Cleaning, modeling, and shaping data for use",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-load",
				customizedComponent: false,
				name: "Load",
				file: "ETLxELT/04-load.md",
				status: "solid",
				tagline: "Writing data safely into its destination",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-orchestration",
				customizedComponent: false,
				name: "Orchestration & Scheduling",
				file: "ETLxELT/05-orchestration.md",
				status: "solid",
				tagline: "Coordinating dependencies, retries, and reruns",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-streaming",
				customizedComponent: false,
				name: "Streaming & Real-Time Processing",
				file: "ETLxELT/06-streaming.md",
				status: "solid",
				tagline: "Processing events continuously and reliably",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-data-quality",
				customizedComponent: false,
				name: "Data Quality & Testing",
				file: "ETLxELT/07-data-quality.md",
				status: "solid",
				tagline: "Proving pipeline outputs are trustworthy",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-architecture-patterns",
				customizedComponent: false,
				name: "Architecture & Design Patterns",
				file: "ETLxELT/08-architecture-patterns.md",
				status: "solid",
				tagline: "Structuring data platforms for scale and change",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-performance",
				customizedComponent: false,
				name: "Performance & Optimization",
				file: "ETLxELT/09-performance.md",
				status: "solid",
				tagline: "Making pipelines faster and more economical",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-monitoring-observability",
				customizedComponent: false,
				name: "Monitoring, Observability & Lineage",
				file: "ETLxELT/10-monitoring-observability.md",
				status: "solid",
				tagline: "Seeing pipeline health before users report it",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-security-governance",
				customizedComponent: false,
				name: "Security & Governance",
				file: "ETLxELT/11-security-governance.md",
				status: "solid",
				tagline: "Protecting data and controlling how it is used",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-tools-landscape",
				customizedComponent: false,
				name: "Tools & Platforms Landscape",
				file: "ETLxELT/12-tools-landscape.md",
				status: "solid",
				tagline: "Comparing the building blocks of a modern data stack",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-quick-reference",
				customizedComponent: false,
				name: "Quick Reference",
				file: "ETLxELT/13-quick-reference.md",
				status: "solid",
				tagline: "Fast lookup for common ETL/ELT decisions and commands",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "etl-worked-examples",
				customizedComponent: true,
				name: "Worked Examples",
				file: "ETLxELT/14-worked-examples.md",
				status: "solid",
				tagline: "Production-grade scenarios that combine the full reference",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "infra",
		label: "Infrastructure",
		items: [
			{
				id: "dbt",
				customizedComponent: false,
				name: "dbt",
				file: "Infrastructure/dbt_Cheatsheet.md",
				status: "solid",
				tagline: "Project structure, materializations, snapshots, tests",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "kafka",
				customizedComponent: false,
				name: "Kafka",
				file: "Infrastructure/kafka.md",
				status: "solid",
				tagline: "Deep and code-heavy, but styled differently from the rest",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "redis",
				customizedComponent: false,
				name: "Redis",
				file: "Infrastructure/redis.md",
				status: "solid",
				tagline: "2,800+ lines — data types, production patterns, tuning",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "terraform",
				customizedComponent: false,
				name: "Terraform",
				file: "Infrastructure/Terraform.md",
				status: "solid",
				tagline: "Infrastructure as code for provisioning the data stack",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "docker",
				customizedComponent: false,
				name: "Docker",
				file: "Infrastructure/docker.md",
				status: "solid",
				tagline:
					"Containerizing pipelines, notebooks, and the tools already in this index",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "airflow",
				customizedComponent: false,
				name: "Apache Airflow",
				file: "Infrastructure/Airflow.md",
				status: "solid",
				tagline:
					"DAGs, operators, sensors, XComs — tool-specific companion to your ETL orchestration concepts",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "kubernetes",
				customizedComponent: false,
				name: "Kubernetes",
				file: "Infrastructure/Kubernetes.md",
				status: "solid",
				tagline:
					"Complements Docker; how production pipelines actually get run at scale",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "great-expectations",
				customizedComponent: false,
				name: "Great Expectations",
				file: "Infrastructure/Great_Expectations.md",
				status: "solid",
				tagline:
					'Tool-specific data quality/validation, companion to ETL "Data Quality & Testing"',
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "git-github",
				customizedComponent: false,
				name: "Git & GitHub",
				file: "Infrastructure/git.md",
				status: "solid",
				tagline: "Branching, PR workflows, conflict resolution",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "cicd-data-pipelines",
				customizedComponent: false,
				name: "CI/CD for Data Pipelines",
				file: "Infrastructure/CICD_for_Data_Pipelines.md",
				status: "solid",
				tagline:
					"GitHub Actions/GitLab CI — testing & deploying dbt/Airflow projects",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "linux-bash",
				customizedComponent: false,
				name: "Linux / Bash / Shell Scripting",
				file: "Infrastructure/Linux_Bash.md",
				status: "solid",
				tagline: "Cron, piping, file ops — unavoidable in real pipeline work",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "sysdesign",
		label: "System Design for Data Engineers",
		items: [
			{
				id: "sysdesign-framework",
				customizedComponent: false,
				name: "Interview Framework",
				file: "System Design/01-framework.md",
				status: "solid",
				tagline:
					"Requirements → scale estimation → high-level design → deep dive",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-scale-estimation",
				customizedComponent: false,
				name: "Scale & Capacity Estimation",
				file: "System Design/02-scale-estimation.md",
				status: "solid",
				tagline:
					"Back-of-envelope math: events/day → throughput, storage, cost",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-storage-file-formats",
				customizedComponent: false,
				name: "Storage & File Formats",
				file: "System Design/03-storage-file-formats.md",
				status: "solid",
				tagline:
					"Parquet vs. ORC vs. Avro, partitioning, and the small-file problem",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-batch-streaming",
				customizedComponent: false,
				name: "Batch vs. Streaming vs. Hybrid Design",
				file: "System Design/04-batch-streaming-hybrid.md",
				status: "solid",
				tagline: "Choosing an architecture shape once scale is known",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-cdc-idempotent-processing",
				customizedComponent: false,
				name: "CDC & Idempotent Processing",
				file: "System Design/05-cdc-idempotent-processing.md",
				status: "solid",
				tagline:
					"Capturing source-system changes without duplicating or losing data",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-fault-tolerance",
				customizedComponent: false,
				name: "Designing for Fault Tolerance",
				file: "System Design/06-fault-tolerance.md",
				status: "solid",
				tagline: "Idempotency, exactly-once semantics, replay",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-data-quality-observability",
				customizedComponent: false,
				name: "Data Quality, Contracts & Observability",
				file: "System Design/07-data-quality-observability.md",
				status: "solid",
				tagline:
					"Schema contracts, freshness SLAs, and catching bad data before it spreads",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-security-governance-multitenancy",
				customizedComponent: false,
				name: "Security, Governance & Multi-Tenancy",
				file: "System Design/08-security-governance-multitenancy.md",
				status: "solid",
				tagline:
					"Access control, PII handling, and isolating tenants on shared infrastructure",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-metadata-catalog-design",
				customizedComponent: false,
				name: "Metadata & Catalog Design",
				file: "System Design/09-metadata-catalog-design.md",
				status: "solid",
				tagline: "Making a growing platform discoverable and auditable",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-followups",
				customizedComponent: false,
				name: "Common Follow-ups & Trade-off Talk Tracks",
				file: "System Design/10-followups-tradeoffs.md",
				status: "solid",
				tagline: "How to reason out loud when the interviewer pushes back",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sysdesign-case-studies",
				customizedComponent: true,
				name: "Worked Case Studies",
				file: "System Design/11-worked-case-studies.md",
				status: "solid",
				tagline:
					"Full prompts combining framework, scale, architecture, and fault tolerance",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	// ---- Cloud Platforms ----
	{
		key: "cloud",
		label: "Cloud Platforms for Data Engineering",
		slug: "cloud-platforms",
		subcategories: [
			{
				key: "databricks",
				label: "Databricks",
				slug: "databricks",
				status: "solid",
				tagline:
					"Spark, Delta Lake, Lakeflow, Unity Catalog, and platform operations",
				covers: "",
				items: [
					{
						id: "databricks",
						customizedComponent: false,
						name: "Databricks Overview",
						file: "Databricks/Databricks_Cheatsheet.md",
						status: "solid",
						slug: "overview",
						tagline: "Notebooks, clusters, Delta Live Tables, Unity Catalog",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-spark-architecture-runtime",
						customizedComponent: false,
						name: "Spark Architecture & Runtime",
						file: "Databricks/Spark_Architecture_Runtime.md",
						status: "solid",
						slug: "spark-architecture-runtime",
						tagline: "Spark internals, AQE, Photon, shuffles, joins",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-delta-table-deep-dive",
						customizedComponent: false,
						name: "Delta Table Deep Dive",
						file: "Databricks/Delta_Table_Deep_Dive.md",
						status: "solid",
						slug: "delta-table-deep-dive",
						tagline:
							"Format internals, constraints, CDF, cloning, liquid clustering",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-ingestion-etl-dlt",
						customizedComponent: false,
						name: "Ingestion, ETL & DLT",
						file: "Databricks/Ingestion_ETL_DLT.md",
						status: "solid",
						slug: "ingestion-etl-dlt",
						tagline: "Auto Loader, DLT/Lakeflow, medallion architecture",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-unity-catalog-governance",
						customizedComponent: false,
						name: "Unity Catalog & Governance",
						file: "Databricks/Unity_Catalog_Governance.md",
						status: "solid",
						slug: "unity-catalog-governance",
						tagline:
							"Metastore, RBAC, lineage, row/column security, Delta Sharing",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-orchestration-workflows",
						customizedComponent: false,
						name: "Orchestration & Workflows",
						file: "Databricks/Orchestration_Workflows.md",
						status: "solid",
						slug: "orchestration-workflows",
						tagline:
							"Jobs, dependencies, triggers, alerting, multi-task orchestration",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-performance-tuning-optimization",
						customizedComponent: false,
						name: "Performance Tuning & Optimization",
						file: "Databricks/Performance_Tuning_Optimization.md",
						status: "solid",
						slug: "performance-tuning-optimization",
						tagline:
							"Query optimization, skew, caching, file sizing, broadcast joins",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-cluster-compute-management",
						customizedComponent: false,
						name: "Cluster & Compute Management",
						file: "Databricks/Cluster_Compute_Management.md",
						status: "solid",
						slug: "cluster-compute-management",
						tagline: "Policies, pools, autoscaling, instance types",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-devops-cicd",
						customizedComponent: false,
						name: "DevOps & CI/CD",
						file: "Databricks/DevOps_CICD.md",
						status: "solid",
						slug: "devops-cicd",
						tagline: "CLI, Asset Bundles, Repos, Terraform",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-cost-governance-troubleshooting",
						customizedComponent: false,
						name: "Cost, Governance & Troubleshooting",
						file: "Databricks/Databricks_Cost_Governance_Troubleshooting.md",
						status: "solid",
						slug: "cost-governance-troubleshooting",
						tagline: "System tables, debugging, credit and DBU tracking",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "databricks-mlflow-ml",
						customizedComponent: false,
						name: "MLflow & ML",
						file: "Databricks/MLflow_ML.md",
						status: "solid",
						slug: "mlflow-ml",
						tagline: "Experiment tracking, registry, serving",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "snowflake",
				label: "Snowflake",
				slug: "snowflake",
				status: "planned",
				tagline:
					"Architecture, micro-partitions, ingestion, governance, and cost control",
				covers: "",
				items: [
					{
						id: "snowflake",
						customizedComponent: false,
						name: "Snowflake Cheatsheet",
						file: "Databases/Snowflake_Cheatsheet.md",
						status: "solid",
						slug: "cheatsheet",
						tagline: "Warehouses, loading, Time Travel, Streams & Tasks, RBAC",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-architecture-runtime",
						customizedComponent: false,
						name: "Snowflake Architecture & Runtime",
						file: "Snowflake/Snowflake_Architecture_Runtime.md",
						status: "planned",
						slug: "architecture-runtime",
						tagline: "Micro-partitions, query compiler, caching layers",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-table-micro-partitions-timetravel",
						customizedComponent: false,
						name: "Tables, Micro-Partitions & Time Travel",
						file: "Snowflake/Table_MicroPartitions_TimeTravel.md",
						status: "planned",
						slug: "table-micro-partitions-time-travel",
						tagline: "Clustering keys, Time Travel, Streams, zero-copy cloning",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-ingestion-cdc-orchestration",
						customizedComponent: false,
						name: "Ingestion, CDC & Orchestration",
						file: "Snowflake/Ingestion_CDC_Orchestration.md",
						status: "planned",
						slug: "ingestion-cdc-orchestration",
						tagline: "Snowpipe, Snowpipe Streaming, COPY INTO, Streams & Tasks",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-data-sharing-security-governance",
						customizedComponent: false,
						name: "Data Sharing, Security & Governance",
						file: "Snowflake/Data_Sharing_Security_Governance.md",
						status: "planned",
						slug: "data-sharing-security-governance",
						tagline:
							"RBAC, masking and row-access policies, tags, Secure Data Sharing",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-performance-tuning-optimization",
						customizedComponent: false,
						name: "Performance Tuning & Optimization",
						file: "Snowflake/Performance_Tuning_Optimization.md",
						status: "planned",
						slug: "performance-tuning-optimization",
						tagline:
							"Query profile, clustering strategy, caching, warehouse sizing",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-warehouse-compute-management",
						customizedComponent: false,
						name: "Warehouse & Compute Management",
						file: "Snowflake/Warehouse_Compute_Management.md",
						status: "planned",
						slug: "warehouse-compute-management",
						tagline:
							"Virtual warehouses, multi-cluster scaling, resource monitors",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-devops-cicd",
						customizedComponent: false,
						name: "DevOps & CI/CD",
						file: "Snowflake/DevOps_CICD.md",
						status: "planned",
						slug: "devops-cicd",
						tagline:
							"SnowSQL/CLI, schemachange, Terraform, dbt, Git integration",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-cost-governance-troubleshooting",
						customizedComponent: false,
						name: "Cost, Governance & Troubleshooting",
						file: "Snowflake/Snowflake_Cost_Governance_Troubleshooting.md",
						status: "planned",
						slug: "cost-governance-troubleshooting",
						tagline: "ACCOUNT_USAGE, query profile, credit consumption",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "snowflake-snowpark-cortex-ml",
						customizedComponent: false,
						name: "Snowpark, Cortex & ML",
						file: "Snowflake/Snowpark_Cortex_ML.md",
						status: "planned",
						slug: "snowpark-cortex-ml",
						tagline: "Snowpark ML, Cortex functions, Model Registry",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "aws",
				label: "AWS",
				slug: "aws",
				status: "solid",
				tagline:
					"The original cloud data stack — storage, ETL, warehousing, and orchestration on AWS",
				covers: "",
				items: [
					{
						id: "s3",
						customizedComponent: false,
						name: "Amazon S3",
						file: "AWS/S3.md",
						slug: "s3",
						status: "solid",
						tagline: "Object storage as the data lake foundation",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "glue",
						customizedComponent: false,
						name: "AWS Glue",
						file: "AWS/Glue.md",
						slug: "glue",
						status: "solid",
						tagline: "Serverless ETL, Data Catalog, and crawlers",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "redshift",
						customizedComponent: false,
						name: "Amazon Redshift",
						file: "AWS/Redshift.md",
						slug: "redshift",
						status: "solid",
						tagline:
							"The AWS data warehouse — distribution styles, sort keys, Spectrum",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "emr",
						customizedComponent: false,
						name: "Amazon EMR",
						file: "AWS/EMR.md",
						slug: "emr",
						status: "solid",
						tagline:
							"Managed Hadoop/Spark clusters for when Glue\u2019s limits don\u2019t fit",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "athena",
						customizedComponent: false,
						name: "Amazon Athena",
						file: "AWS/Athena.md",
						slug: "athena",
						status: "solid",
						tagline: "Serverless SQL over S3, no infrastructure to manage",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "lambda",
						customizedComponent: false,
						name: "AWS Lambda",
						file: "AWS/Lambda.md",
						slug: "lambda",
						status: "solid",
						tagline:
							"Event-driven compute for glue code, triggers, and lightweight transforms",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "kinesis",
						customizedComponent: false,
						name: "Amazon Kinesis",
						file: "AWS/Kinesis.md",
						slug: "kinesis",
						status: "solid",
						tagline:
							"Managed streaming — Data Streams, Firehose, and Analytics compared",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "stepfunctions",
						customizedComponent: false,
						name: "AWS Step Functions",
						file: "AWS/Step Functions.md",
						slug: "step-functions",
						status: "solid",
						tagline:
							"Serverless orchestration — state machines for pipeline coordination",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "mwaa",
						customizedComponent: false,
						name: "Amazon MWAA (Managed Airflow)",
						file: "AWS/MWAA.md",
						slug: "mwaa",
						status: "solid",
						tagline:
							"Managed Apache Airflow, without running your own scheduler",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "gcp",
				label: "GCP",
				slug: "gcp",
				status: "planned",
				tagline:
					"Google Cloud's data stack — BigQuery, Dataflow, Pub/Sub, Dataproc, Composer",
				covers: "",
				items: [
					{
						id: "gcp-bigquery",
						customizedComponent: false,
						name: "Google BigQuery",
						file: "GCP/BigQuery.md",
						slug: "bigquery",
						status: "planned",
						tagline: "Serverless warehouse — partitioning, clustering, slots",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dataflow",
						customizedComponent: false,
						name: "Dataflow",
						file: "GCP/Dataflow.md",
						status: "planned",
						slug: "dataflow",
						tagline: "Managed Apache Beam — batch & streaming pipelines",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "pubsub",
						customizedComponent: false,
						name: "Pub/Sub",
						file: "GCP/PubSub.md",
						slug: "pubsub",
						status: "planned",
						tagline:
							"Managed messaging for event-driven and streaming architectures",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "dataproc",
						customizedComponent: false,
						name: "Dataproc",
						file: "GCP/Dataproc.md",
						slug: "dataproc",
						status: "planned",
						tagline: "Managed Hadoop/Spark clusters, GCP's answer to EMR",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "cloud-composer",
						customizedComponent: false,
						name: "Cloud Composer",
						file: "GCP/Cloud_Composer.md",
						slug: "cloud-composer",
						status: "planned",
						tagline: "Managed Airflow on GCP",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "azure",
				label: "Azure",
				slug: "azure",
				status: "planned",
				tagline:
					"Microsoft's data stack — Data Factory, Synapse, Databricks on Azure",
				covers: "",
				items: [
					{
						id: "azure-data-factory",
						customizedComponent: false,
						name: "Azure Data Factory",
						file: "Azure/Data_Factory.md",
						slug: "azure-data-factory",
						status: "planned",
						tagline: "Cloud ETL/orchestration, pipelines and data flows",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "azure-synapse",
						customizedComponent: false,
						name: "Azure Synapse Analytics",
						file: "Azure/Synapse_Analytics.md",
						status: "planned",
						slug: "azure-synapse",
						tagline: "Unified warehouse + big data analytics",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "azure-databricks",
						customizedComponent: false,
						name: "Azure Databricks",
						file: "Azure/Databricks.md",
						status: "planned",
						slug: "azure-databricks",
						tagline: "Managed Spark/Databricks on Azure",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
		],
	},
	// ---- Data Science, Machine Learning & Analytics ----
	{
		key: "ds",
		label: "Data Science & Statistics",
		items: [
			{
				id: "abtesting",
				customizedComponent: false,
				name: "A/B Testing — 50 Problems",
				file: "AB_Testing_50_Problems.md",
				status: "solid",
				tagline: "50 worked scenarios across a wide range of industries",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "oneliners",
				customizedComponent: false,
				name: "Python One-Liners",
				file: "1000_plus_python_one_liners.md",
				status: "solid",
				tagline: "1,020 one-liners across 52 categories",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "charts",
				customizedComponent: false,
				name: "Data Visualization",
				file: "Data Visualization/Master_Cheatsheet.md",
				status: "solid",
				tagline: "103 chart types across matplotlib, seaborn & plotly",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "mathstats",
				customizedComponent: true,
				name: "Math & Statistics",
				file: "Math_and_Statistics.md",
				status: "solid",
				tagline:
					"The stats and applied math the A/B Testing and Clustering sheets assume you have",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "eda",
				customizedComponent: true,
				name: "Exploratory Data Analysis (EDA)",
				status: "solid",
				tagline: "A structured workflow for understanding data before modeling",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "statistical-inference",
				customizedComponent: false,
				name: "Statistical Inference & Hypothesis Testing",
				file: "Statistical_Inference_and_Hypothesis_Testing.md",
				status: "solid",
				tagline:
					"Dedicated foundations sheet — the layer your A/B Testing sheet assumes",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "ml",
		label: "Machine Learning",
		slug: "machine-learning",
		subcategories: [
			{
				key: "core-ml",
				label: "Core & Classical ML",
				slug: "core-ml",
				status: "planned",
				tagline:
					"Classical supervised & unsupervised learning — algorithms, sklearn, evaluation, tuning",
				covers: "",
				items: [
					{
						id: "featureeng",
						customizedComponent: true,
						name: "Feature Engineering",
						file: "Feature_Engineering.md",
						status: "solid",
						slug: "featureeng",
						tagline:
							"Encoding, scaling, and the leakage traps that break models in production",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "ml-algorithms",
						customizedComponent: false,
						name: "Machine Learning Algorithms",
						file: "Machine_Learning_Algorithms.md",
						status: "planned",
						slug: "ml-algorithms",
						tagline: "Regression, decision trees, ensembles, SVMs",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "sklearn-general",
						customizedComponent: false,
						name: "Scikit-learn (General)",
						file: "Scikit_learn_General.md",
						status: "planned",
						slug: "sklearn-general",
						tagline:
							"Pipelines, cross-validation, hyperparameter tuning — beyond clustering",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "model-evaluation",
						customizedComponent: false,
						name: "Model Evaluation & Metrics",
						file: "Model_Evaluation_and_Metrics.md",
						status: "planned",
						slug: "model-evaluation",
						tagline:
							"Precision/recall/ROC-AUC, confusion matrices, calibration",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "clustering",
						customizedComponent: false,
						name: "Clustering Problems",
						file: "clustering_100_problems.md",
						status: "solid",
						slug: "clustering",
						tagline:
							"75 self-contained scikit-learn problems, Beginner → Advanced",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "xgboost-lightgbm",
						customizedComponent: false,
						name: "XGBoost / LightGBM",
						file: "XGBoost_LightGBM_Cheatsheet.md",
						status: "planned",
						slug: "xgboost-lightgbm",
						tagline:
							"Gradient boosting — the most-used tabular ML approach in practice",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "model-interpretability",
						customizedComponent: false,
						name: "Model Interpretability & Explainability",
						file: "Model_Interpretability_and_Explainability.md",
						status: "planned",
						slug: "model-interpretability",
						tagline:
							"SHAP, LIME, partial dependence — explaining what a model actually learned",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "hyperparameter-optimization-automl",
						customizedComponent: false,
						name: "Hyperparameter Optimization & AutoML",
						file: "Hyperparameter_Optimization_and_AutoML.md",
						status: "planned",
						slug: "hyperparameter-optimization-automl",
						tagline:
							"Grid/random search, Bayesian optimization (Optuna), and when AutoML earns its keep",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "deep-learning-nlp",
				label: "Deep Learning & NLP",
				slug: "deep-learning-nlp",
				status: "planned",
				tagline: "Neural networks, NLP, and computer vision fundamentals",
				covers: "",
				items: [
					{
						id: "deep-learning-basics",
						customizedComponent: false,
						name: "Deep Learning Basics",
						file: "Deep_Learning_Basics.md",
						status: "planned",
						slug: "deep-learning-basics",
						tagline: "Neural nets, PyTorch/TensorFlow/Keras fundamentals",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "nlp-fundamentals",
						customizedComponent: false,
						name: "NLP Fundamentals",
						file: "NLP_Fundamentals.md",
						status: "planned",
						slug: "nlp-fundamentals",
						tagline: "Tokenization, embeddings, TF-IDF, transformers overview",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "computer-vision-fundamentals",
						customizedComponent: false,
						name: "Computer Vision Fundamentals",
						file: "Computer_Vision_Fundamentals.md",
						status: "planned",
						slug: "computer-vision-fundamentals",
						tagline:
							"CNNs, image preprocessing, and transfer learning for image tasks",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "advanced-deep-learning",
				label: "Advanced Deep Learning",
				slug: "advanced-deep-learning",
				status: "planned",
				tagline:
					"Beyond the basics — attention mechanisms, generative vision models, graphs, and self-supervision",
				covers: "",
				items: [
					{
						id: "sequence-models-attention",
						customizedComponent: false,
						name: "Sequence Models & Attention",
						file: "Sequence_Models_and_Attention.md",
						status: "planned",
						slug: "sequence-models-attention",
						tagline:
							"RNNs, LSTMs, and the attention mechanism that replaced them",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "generative-vision-models",
						customizedComponent: false,
						name: "Generative Models for Vision",
						file: "Generative_Models_for_Vision.md",
						status: "planned",
						slug: "generative-vision-models",
						tagline:
							"GANs, VAEs, and diffusion models — how each generates images",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "graph-neural-networks",
						customizedComponent: false,
						name: "Graph Neural Networks & Graph ML",
						file: "Graph_Neural_Networks_and_Graph_ML.md",
						status: "planned",
						slug: "graph-neural-networks",
						tagline:
							"Learning on graph-structured data — GCNs, GraphSAGE, and graph embeddings",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "self-supervised-multimodal-learning",
						customizedComponent: false,
						name: "Self-Supervised & Multimodal Learning",
						file: "Self_Supervised_and_Multimodal_Learning.md",
						status: "planned",
						slug: "self-supervised-multimodal-learning",
						tagline:
							"Learning from unlabeled data, and models that connect text, images, and audio",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "generative-ai-llms",
				label: "Generative AI & LLMs",
				slug: "generative-ai-llms",
				status: "planned",
				tagline:
					"Large language models — prompting, fine-tuning, retrieval, and evaluation",
				covers: "",
				items: [
					{
						id: "llm-fundamentals-prompting",
						customizedComponent: false,
						name: "LLM Fundamentals & Prompt Engineering",
						file: "LLM_Fundamentals_and_Prompt_Engineering.md",
						status: "planned",
						slug: "llm-fundamentals-prompting",
						tagline:
							"How LLMs generate text, and prompting patterns that reliably improve output",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "finetuning-peft",
						customizedComponent: false,
						name: "Fine-tuning & PEFT",
						file: "Fine_tuning_and_PEFT.md",
						status: "planned",
						slug: "finetuning-peft",
						tagline:
							"LoRA, QLoRA, and adapters — adapting a pretrained model without retraining it",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "rag-vector-search",
						customizedComponent: false,
						name: "RAG & Vector Search",
						file: "RAG_and_Vector_Search.md",
						status: "planned",
						slug: "rag-vector-search",
						tagline:
							"Grounding LLM outputs in real data with retrieval and embeddings",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "llm-evaluation-safety",
						customizedComponent: false,
						name: "LLM Evaluation & Safety",
						file: "LLM_Evaluation_and_Safety.md",
						status: "planned",
						slug: "llm-evaluation-safety",
						tagline:
							"Benchmarks, hallucination detection, and guardrails for generative systems",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "reinforcement-learning",
				label: "Reinforcement Learning",
				slug: "reinforcement-learning",
				status: "planned",
				tagline:
					"Sequential decision-making — from tabular Q-learning to deep policy-gradient methods",
				covers: "",
				items: [
					{
						id: "rl-fundamentals",
						customizedComponent: false,
						name: "RL Fundamentals",
						file: "RL_Fundamentals.md",
						status: "planned",
						slug: "rl-fundamentals",
						tagline:
							"MDPs, Q-learning, and the exploration/exploitation tradeoff",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "deep-rl",
						customizedComponent: false,
						name: "Deep Reinforcement Learning",
						file: "Deep_Reinforcement_Learning.md",
						status: "planned",
						slug: "deep-rl",
						tagline:
							"DQN, policy gradients, and actor-critic methods for large state spaces",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "specialized-ml",
				label: "Specialized ML Applications",
				slug: "specialized-ml",
				status: "planned",
				tagline:
					"Recommenders, anomaly detection, time series, and causal inference — applied ML beyond generic classifiers",
				covers: "",
				items: [
					{
						id: "recommender-systems",
						customizedComponent: false,
						name: "Recommender Systems",
						file: "Recommender_Systems.md",
						status: "planned",
						slug: "recommender-systems",
						tagline:
							"Collaborative filtering, matrix factorization, content-based approaches",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "anomaly-detection-imbalanced-learning",
						customizedComponent: false,
						name: "Anomaly Detection & Imbalanced Learning",
						file: "Anomaly_Detection_and_Imbalanced_Learning.md",
						status: "planned",
						slug: "anomaly-detection-imbalanced-learning",
						tagline:
							"Isolation forests, autoencoders, and modeling rare-event data honestly",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "time-series-forecasting",
						customizedComponent: false,
						name: "Time Series Analysis & Forecasting",
						file: "Time_Series_Analysis_and_Forecasting.md",
						status: "planned",
						slug: "time-series-forecasting",
						tagline: "ARIMA, Prophet, seasonality/decomposition",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "causal-inference-ml",
						customizedComponent: false,
						name: "Causal Inference for ML",
						file: "Causal_Inference_for_ML.md",
						status: "planned",
						slug: "causal-inference-ml",
						tagline:
							"Estimating treatment effects and uplift when correlation isn't enough",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
			{
				key: "mlops-production",
				label: "MLOps & Production",
				slug: "mlops-production",
				status: "planned",
				tagline:
					"Feature stores, serving, distributed training, and monitoring — keeping a model alive after it ships",
				covers: "",
				items: [
					{
						id: "mlops",
						customizedComponent: false,
						name: "MLOps",
						file: "MLOps_Cheatsheet.md",
						status: "planned",
						slug: "mlops",
						tagline:
							"Model versioning, deployment, monitoring, drift detection",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "feature-stores-ml-pipelines",
						customizedComponent: false,
						name: "Feature Stores & ML Data Pipelines",
						file: "Feature_Stores_and_ML_Data_Pipelines.md",
						status: "planned",
						slug: "feature-stores-ml-pipelines",
						tagline:
							"Feature stores, training/serving skew, and data pipelines built for ML",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "model-serving-deployment",
						customizedComponent: false,
						name: "Model Serving & Deployment",
						file: "Model_Serving_and_Deployment.md",
						status: "planned",
						slug: "model-serving-deployment",
						tagline: "Turning a trained model into a fast, reliable API",
						covers: "",
						fixes: [],
						extend: [],
					},
					{
						id: "distributed-training-scaling",
						customizedComponent: false,
						name: "Distributed & Large-Scale Training",
						file: "Distributed_and_Large_Scale_Training.md",
						status: "planned",
						slug: "distributed-training-scaling",
						tagline:
							"Data parallelism, model parallelism, and mixed precision for training at scale",
						covers: "",
						fixes: [],
						extend: [],
					},
				],
			},
		],
	},
	{
		key: "bi",
		label: "Business Intelligence & Analytics Tools",
		items: [
			{
				id: "excel-sheets-advanced",
				customizedComponent: false,
				name: "Excel / Google Sheets (Advanced)",
				file: "Excel_Google_Sheets_Advanced.md",
				status: "planned",
				tagline: "Pivot tables, Power Query, array formulas, VBA basics",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "tableau",
				customizedComponent: false,
				name: "Tableau",
				file: "Tableau_Cheatsheet.md",
				status: "planned",
				tagline: "Calculated fields, LOD expressions, dashboard actions",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "powerbi-dax",
				customizedComponent: false,
				name: "Power BI / DAX",
				file: "Power_BI_DAX_Cheatsheet.md",
				status: "planned",
				tagline: "Data model relationships, measures vs calculated columns",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "looker-lookml",
				customizedComponent: false,
				name: "Looker / LookML",
				file: "Looker_LookML_Cheatsheet.md",
				status: "planned",
				tagline: "Modeling layer for BI, explores, views",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "ga4",
				customizedComponent: false,
				name: "Google Analytics 4",
				file: "Google_Analytics_4_Cheatsheet.md",
				status: "planned",
				tagline: "Events, funnels, attribution models",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "dashboard-storytelling",
				customizedComponent: false,
				name: "Dashboard & Data Storytelling Principles",
				file: "Dashboard_and_Data_Storytelling_Principles.md",
				status: "planned",
				tagline:
					"Chart choice, pre-attentive attributes, avoiding misleading visuals",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	// ---- Career Tracks ----
	{
		key: "analytics-eng",
		label: "Analytics Engineer",
		items: [
			{
				id: "dbt-semantic-layer",
				customizedComponent: false,
				name: "dbt Semantic Layer / MetricFlow",
				file: "dbt_Semantic_Layer_MetricFlow.md",
				status: "planned",
				tagline: "Define metrics once, query consistently across BI tools",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "cubejs",
				customizedComponent: false,
				name: "Cube.js",
				file: "CubeJS_Cheatsheet.md",
				status: "planned",
				tagline: "Headless BI / semantic layer alternative to dbt's",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "cicd-analytics-code",
				customizedComponent: false,
				name: "CI/CD for Analytics Code",
				file: "CICD_for_Analytics_Code.md",
				status: "planned",
				tagline: "Testing and deploying dbt models safely through PRs",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "sql-version-control",
				customizedComponent: false,
				name: "SQL Version Control Workflows",
				file: "SQL_Version_Control_Workflows.md",
				status: "planned",
				tagline: "Branching, code review, and environments for analytics repos",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "data-contracts",
				customizedComponent: false,
				name: "Data Contracts",
				file: "Data_Contracts.md",
				status: "planned",
				tagline:
					"Formal agreements between producers and consumers of a dataset",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "data-architect",
		label: "Data Architect",
		items: [
			{
				id: "data-mesh",
				customizedComponent: false,
				name: "Data Mesh",
				file: "Data_Mesh.md",
				status: "planned",
				tagline:
					"Domain-oriented, decentralized data ownership and architecture",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "data-fabric",
				customizedComponent: false,
				name: "Data Fabric",
				file: "Data_Fabric.md",
				status: "planned",
				tagline: "Unified data access layer across distributed sources",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "medallion-architecture",
				customizedComponent: false,
				name: "Medallion Architecture",
				file: "Medallion_Architecture.md",
				status: "planned",
				tagline: "Bronze/Silver/Gold layering for lakehouse pipelines",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "data-governance-frameworks",
				customizedComponent: false,
				name: "Data Governance Frameworks",
				file: "Data_Governance_Frameworks.md",
				status: "planned",
				tagline: "Policies, stewardship, and data cataloging at scale",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "mdm",
				customizedComponent: false,
				name: "Master Data Management (MDM)",
				file: "Master_Data_Management.md",
				status: "planned",
				tagline: "Single source of truth for core business entities",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "enterprise-architecture-patterns",
				customizedComponent: false,
				name: "Enterprise Architecture Patterns",
				file: "Enterprise_Architecture_Patterns.md",
				status: "planned",
				tagline: "How data platforms fit into the broader org/tech landscape",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "dba",
		label: "Database Administrator (DBA)",
		items: [
			{
				id: "backup-recovery",
				customizedComponent: false,
				name: "Backup & Recovery",
				file: "Backup_and_Recovery.md",
				status: "planned",
				tagline: "Full/incremental backups, point-in-time recovery strategies",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "replication-failover",
				customizedComponent: false,
				name: "Replication & Failover",
				file: "Replication_and_Failover.md",
				status: "planned",
				tagline: "Master-replica setups, high availability, automatic failover",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "query-plan-performance-tuning",
				customizedComponent: false,
				name: "Query Plan & Performance Tuning",
				file: "Query_Plan_and_Performance_Tuning.md",
				status: "planned",
				tagline: "Reading execution plans, index internals, query optimization",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "postgres-vacuuming-maintenance",
				customizedComponent: false,
				name: "Vacuuming & Maintenance (PostgreSQL)",
				file: "PostgreSQL_Vacuuming_and_Maintenance.md",
				status: "planned",
				tagline: "Autovacuum tuning, bloat management, routine upkeep",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "ha-dr",
				customizedComponent: false,
				name: "High Availability & Disaster Recovery",
				file: "High_Availability_and_Disaster_Recovery.md",
				status: "planned",
				tagline: "RTO/RPO planning, multi-region setups",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "db-user-access-management",
				customizedComponent: false,
				name: "User & Access Management",
				file: "User_and_Access_Management.md",
				status: "planned",
				tagline: "Roles, permissions, auditing at the database engine level",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
	{
		key: "bi-developer",
		label: "BI Developer",
		items: [
			{
				id: "dashboard-architecture",
				customizedComponent: false,
				name: "Dashboard Architecture",
				file: "Dashboard_Architecture.md",
				status: "planned",
				tagline: "Structuring reports/dashboards for performance and reuse",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "row-level-security-bi",
				customizedComponent: false,
				name: "Row-Level Security",
				file: "Row_Level_Security_BI.md",
				status: "planned",
				tagline:
					"Restricting data visibility by user/role within Power BI, Tableau, etc.",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "powerbi-deep-dive",
				customizedComponent: false,
				name: "Power BI Deep Dive",
				file: "Power_BI_Deep_Dive.md",
				status: "planned",
				tagline: "Data model design, DAX patterns, deployment pipelines",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "tableau-deep-dive",
				customizedComponent: false,
				name: "Tableau Deep Dive",
				file: "Tableau_Deep_Dive.md",
				status: "planned",
				tagline:
					"LOD expressions, extracts vs live connections, server administration",
				covers: "",
				fixes: [],
				extend: [],
			},
			{
				id: "semantic-modeling-bi",
				customizedComponent: false,
				name: "Semantic Modeling for BI",
				file: "Semantic_Modeling_for_BI.md",
				status: "planned",
				tagline:
					"Building the reusable metrics/dimensions layer BI tools sit on",
				covers: "",
				fixes: [],
				extend: [],
			},
		],
	},
];
